"""ajout finder_name et finder_phone

Revision ID: 6b51d56e40cc
Revises: 88cd7328c498
Create Date: 2026-09-13 23:03:19.239817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b51d56e40cc'
down_revision = '88cd7328c498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finder_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finder_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('finder_phone')
        batch_op.drop_column('finder_name')

    # ### end Alembic commands ###
