"""add authority_invites

Revision ID: b8e1baa2a8e3
Revises: 0e5d45c27feb
Create Date: 2026-09-19 02:46:57.966688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e1baa2a8e3'
down_revision = '0e5d45c27feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('agency_name', sa.String(length=150), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_posts_region_id', 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key('fk_posts_country_id', 'countries', ['country_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_region_id', 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key('fk_users_country_id', 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_country_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_region_id', type_='foreignkey')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_country_id', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_region_id', type_='foreignkey')

    op.drop_table('authority_invites')
    # ### end Alembic commands ###