"""fix missing photo column

Revision ID: c1062cdb5114
Revises: 987ee6199e80
Create Date: 2026-09-20 13:42:09.797652

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1062cdb5114'
down_revision = '987ee6199e80'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###